services:
  redis:
    image: redis:7-alpine
    container_name: dev-redis
    command: redis-server --requirepass devpassword --appendonly yes
    ports:
      - "127.0.0.1:16379:6379"
    volumes:
      - ./docker_data:/data
    restart: unless-stopped
    network_mode: bridge
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5