version: '3.8'

services:
  # Caddy web server
  caddy:
    image: caddy:latest
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # Admin API port
      - "9080:8080"  # Test sites (mapped to avoid conflict)
      - "9081:8081"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    networks:
      - caddy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/config/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Caddy MCP Server (lum8rjack/caddy-mcp)
  caddy-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy-mcp-server
    restart: unless-stopped
    ports:
      - "7000:7000"  # MCP server port (for HTTP/SSE transport)
    environment:
      - CADDY_URL=http://caddy:2019  # Internal Docker network communication
      - MCP_TRANSPORT=httpstream     # Can be: stdio, sse, httpstream
      - MCP_PORT=7000
    command: ["./caddy-mcp", "-transport", "httpstream", "-url", "http://caddy:2019", "-port", "7000"]
    networks:
      - caddy-network
    depends_on:
      caddy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "caddy-mcp"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  caddy-network:
    driver: bridge
    name: caddy-mcp-network

volumes:
  caddy_data:
    name: caddy-data
  caddy_config:
    name: caddy-config