services:
  # Caddy web server with Docker provider
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:builder AS builder
        RUN xcaddy build --with github.com/lucaslorentz/caddy-docker-proxy/v2

        FROM caddy:latest
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    container_name: caddy-server
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:2019:2019"  # Admin API port - localhost only for security
      - "127.0.0.1:9080:8080"  # Test sites - localhost only for security
      - "127.0.0.1:9081:8081"  # Test sites - localhost only for security
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Docker socket for auto-discovery
      - ./docker-data/caddy-data:/data
      - ./docker-data/caddy-config:/config
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
      - CADDY_DOCKER_POLLING_INTERVAL=5s
    command: caddy docker-proxy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/config/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s


